
version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    networks:
      - frontend
      - backend
    volumes:
    - ./frontend:/frontend
  backend:
    build:
      context: ./backend
    networks:
      - backend
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "90:80"
    networks:
      - frontend
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=jjl
      - POSTGRES_PASSWORD=jjl
      - POSTGRES_DB=demo
    volumes:
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  frontend:
    # Use a custom driver
    driver: bridge
  backend:
    # Use a custom driver which takes special options
    driver: bridge
