
version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "90:80"
