
version: "3.8"
services:
  frontend:
    command: sh -c "npm install && npx tsc && node dist/index.js"
    build:
      context: ./frontend
    networks:
      - frontend
      - backend
    volumes:
    - ./frontend:/frontend
  backend:
    command: sh -c "npm install && npx tsc && node dist/index.js"
    build:
      context: ./backend
    networks:
      - backend
    volumes:
    - ./backend:/backend
    depends_on:
      - database
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "90:80"
    networks:
      - frontend
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=jjl
      - POSTGRES_PASSWORD=jjl
      - POSTGRES_DB=demo
    volumes:
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./DB/postgres-data:/var/lib/postgresql/data
    networks:
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
