AWSTemplateFormatVersion: '2010-09-09'
Resources:
  JiajunKey:
    Type: AWS::KMS::Key
    Properties:
      KeySpec: RSA_4096
      KeyPolicy:
        Id: key-consolepolicy-3
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::160071257600:root
            Action: kms:*
            Resource: "*"
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::160071257600:role/aws-service-role/cks.kms.amazonaws.com/AWSServiceRoleForKeyManagementServiceCustomKeyStores
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:DescribeKey
              - kms:GetPublicKey
            Resource: "*"
          - Sid: Allow attachment of persistent resources
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::160071257600:role/aws-service-role/cks.kms.amazonaws.com/AWSServiceRoleForKeyManagementServiceCustomKeyStores
            Action:
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
            Resource: "*"
            Condition:
              Bool:
                kms:GrantIsForAWSResource: 'true'
  JiajunAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: 'alias/jiajun-4096-key'
      TargetKeyId: !GetAtt JiajunKey.Arn
